<a href="https://colab.research.google.com/github/MelsonHeo00/Summer_MicroCredential/blob/main/Intro_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 

NumPy (or Numpy) is a Pyhton Library or Module design for Linear Algebra and Statistical Computation.
It is one of the most important modules in python for Data Science since most all of the libraries necessary for  rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to other programming language libraries such as C++. 

_______________________________

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. We will not have the time to cover them all; we will, however, focus on some of the most important topics such as vectors, arrays, matrices, and number generation. Let's start by discussing arrays.

## Numpy Arrays

NumPy arrays are the main objects that we will use in this class. 

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-dimensional arrays and matrices are 2-dimensional (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

### Creating NumPy Arrays From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [ ]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(0,110,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108])

### zeros and ones

Generate arrays of zeros or ones

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((15,15))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [ ]:
np.ones(30)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((30,30))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1

### linspace
Return evenly spaced numbers over a specified interval.

In [ ]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [ ]:
np.random.rand(5)

array([0.39532853, 0.28767256, 0.63723705, 0.81958848, 0.10552333])

In [ ]:
np.random.rand(10,10)

array([[0.75592607, 0.32027948, 0.03774677, 0.51778968, 0.457934  ,
        0.93147896, 0.5319068 , 0.62402026, 0.40365503, 0.67132405],
       [0.88450923, 0.42593345, 0.61866847, 0.48740643, 0.91857095,
        0.30244395, 0.92264687, 0.14247435, 0.01606613, 0.93381843],
       [0.28341242, 0.33066782, 0.313009  , 0.95639412, 0.86752674,
        0.98012814, 0.02840947, 0.28114315, 0.36567471, 0.04502322],
       [0.76821622, 0.70482945, 0.22303135, 0.84708819, 0.53813128,
        0.72475293, 0.50899286, 0.4178185 , 0.14178324, 0.83432446],
       [0.6930306 , 0.2794972 , 0.79093666, 0.68712927, 0.41286361,
        0.09545309, 0.85092   , 0.45825814, 0.09141022, 0.69963027],
       [0.69576628, 0.88624393, 0.12454747, 0.80183198, 0.68566186,
        0.52715625, 0.46118396, 0.47221171, 0.42487931, 0.84994482],
       [0.39593907, 0.69663989, 0.12258968, 0.27626576, 0.77464041,
        0.46521979, 0.41481244, 0.12045694, 0.2333648 , 0.46401901],
       [0.36973058, 0.18989573, 0.8517056

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [ ]:
np.random.randn(20)

array([ 0.15307217, -0.49668995, -0.81589313,  0.21629096, -1.30261164,
       -1.71880462, -1.12814927, -0.61523896, -1.03080909, -1.05664352,
       -0.53076739,  0.37282043,  0.89782094, -0.80127515, -1.25205889,
       -0.59909755,  0.44593657,  0.55894691,  0.05477751, -1.68375432])

In [ ]:
np.random.randn(5,5)

array([[-0.44184508,  1.01064116,  1.99833887,  0.21577714, -0.02530655],
       [ 0.27859028,  0.71287888,  0.91119295,  0.82792409,  1.25512526],
       [ 0.78096458, -1.16099471,  0.58783187,  0.61747119, -0.60430031],
       [ 0.29022728, -2.27124336, -0.10400327, -1.31632786,  0.24033699],
       [-1.90967447,  0.67088679, -0.38483304, -3.10878247, -0.24176113]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [ ]:
np.random.randint(1,500)

48

In [ ]:
np.random.randint(1,1000,100)

array([ 88,  82, 399, 246, 522, 777, 104, 749, 647, 424, 615, 157, 516,
       810, 797, 218, 323, 746, 715, 920, 840, 976, 423, 308,  89, 524,
       341, 629, 113, 123, 299, 835, 693, 352, 111, 137, 734, 133, 989,
       998,  71,  46, 598, 357, 681, 501, 124, 576, 536,  78, 287,  72,
       411, 146, 483, 748, 735, 909, 825, 339, 248,  21, 421, 822,  87,
       370, 210, 569, 620, 704, 774, 995, 364,  16, 685, 501, 993, 777,
        84, 747, 128, 275, 787, 909, 844, 500, 530, 988, 679,  32, 503,
       463, 703,   1,  47, 103,  19, 474, 933, 723])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [ ]:
arr = np.arange(50)
ranarr = np.random.randint(0,500,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
ranarr

array([184, 197, 373, 268,  94, 496, 321, 240,   7, 123])

## Reshape
Returns an array containing the same data with a new shape.

In [ ]:
arr.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr

array([184, 197, 373, 268,  94, 496, 321, 240,   7, 123])

In [ ]:
ranarr.max()

496

In [ ]:
ranarr.argmax()

5

In [ ]:
ranarr.min()

7

In [ ]:
ranarr.argmin()

8

## Shape

Shape is an attribute that arrays have (not a method):

In [ ]:
# Vector
arr.shape

(50,)

In [ ]:
# Notice the two sets of brackets
arr.reshape(2,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr.reshape(2,25).shape

(2, 25)

In [ ]:
arr.reshape(25,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49]])

In [ ]:
arr.reshape(25,2).shape

(25, 2)

### dtype

You can also grab the data type of the object in the array:

In [ ]:
arr.dtype

dtype('int32')

# Good Times!

## Practice

In [ ]:
np.ones(42)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.linspace(0,50,15)

array([ 0.        ,  3.57142857,  7.14285714, 10.71428571, 14.28571429,
       17.85714286, 21.42857143, 25.        , 28.57142857, 32.14285714,
       35.71428571, 39.28571429, 42.85714286, 46.42857143, 50.        ])

In [ ]:
np.random.randn(15)

array([ 0.75067784,  1.59437115, -0.73539308,  0.34596402,  0.27903708,
        1.89829892, -0.02660289,  0.92774339, -0.47049947,  0.26073237,
       -1.87090249,  1.12238085,  2.20550414,  0.67575488,  0.06886952])

In [ ]:
np.random.rand(15,6)

array([[0.91675188, 0.33282412, 0.65098541, 0.38964306, 0.98237323,
        0.70737372],
       [0.00310617, 0.7076111 , 0.75619371, 0.36045148, 0.26405542,
        0.89777381],
       [0.28955765, 0.28465087, 0.08059442, 0.33759919, 0.28905902,
        0.28484108],
       [0.04952105, 0.79398851, 0.0455403 , 0.52530349, 0.85554819,
        0.1413648 ],
       [0.65184621, 0.03453369, 0.23197465, 0.17502143, 0.662376  ,
        0.66563981],
       [0.73833784, 0.91868565, 0.57231189, 0.11347435, 0.64184704,
        0.81863322],
       [0.19977059, 0.83453256, 0.50033371, 0.85693739, 0.68526398,
        0.61069251],
       [0.09128795, 0.01268814, 0.59611748, 0.28466615, 0.41810569,
        0.69368072],
       [0.99475694, 0.55070725, 0.45589619, 0.96448945, 0.59105194,
        0.81353313],
       [0.5235964 , 0.54691986, 0.16319376, 0.27584025, 0.7326374 ,
        0.83224273],
       [0.1477607 , 0.15703145, 0.5172142 , 0.32661339, 0.099635  ,
        0.94504666],
       [0.60957471, 0

In [ ]:
np.random.randint(0,1000,10)

array([168, 843, 385, 215, 247, 366, 248, 848,  55,  10])

In [ ]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
multiplication = np.array(matrix) * np.eye(3)
multiplication

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

In [ ]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
multiplication.dtype

dtype('float64')

In [ ]:
multiplication.min()

0.0

In [ ]:
multiplication.max()

9.0

In [ ]:
np.arange(0,30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
np.arange(0,1000,50)

array([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600,
       650, 700, 750, 800, 850, 900, 950])

In [ ]:
array = np.arange(0,20)

In [ ]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
array.shape

(20,)

In [ ]:
array.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
array.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

# Indexing and Selection

In [ ]:
arr = np.arange(0,15)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Bracket Indexing and Selection
### The simplest way to pick one or some elements of an array looks very similar to python lists:


In [ ]:
arr[8]

8

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

# Broadcasting
### Numpy arrays differ from a normal Python list because of their ability to broadcast:
### The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.


In [ ]:
arr[0:5] = 100

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [ ]:
arr = np.arange(0,20)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
slice_of_arr = arr[0:8]

In [ ]:
slice_of_arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
slice_of_arr[:] = 99

In [ ]:
slice_of_arr

array([99, 99, 99, 99, 99, 99, 99, 99])

In [ ]:
arr # Note: it will occur now in the original way

array([99, 99, 99, 99, 99, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr_copy = arr.copy()
arr_copy
# Data is not copied, it's a view of the original array! This avoids memory problem

array([99, 99, 99, 99, 99, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# Indexing a 2D array (matrices)

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[1] # indexing row

array([20, 25, 30])

In [ ]:
arr_2d[1][0] # getting individual element value

20

In [ ]:
arr_2d[1,0] # getting individual element value

20

In [ ]:
# 2D array slicing
# Shapes 2,2 from the top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
arr_2d[2] # Shape bottom row

array([35, 40, 45])

In [ ]:
arr_2d[2,:] # Shape bottom row

array([35, 40, 45])

# Fancy Indexing
### Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [ ]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
arr_length = arr2d.shape[1]

In [ ]:
for i in range(arr_length):
  arr2d[i] = i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

## Fancy indexing allows the following

In [ ]:
arr2d[[6,2,4,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [ ]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

## More Indexing Help
#### Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:


# Selection
### Let's briefly go over how to use brackets for selection based off of comparison operators.


In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = 2
arr[arr > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# NumPy Operations

## Aritmethic
### You can perform array with array 

In [ ]:
arr = np.arange(0,100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
arr + arr

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [ ]:
arr * arr

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1 / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158,
       0.05      , 0.04761905, 0.04545455, 0.04347826, 0.04166667,
       0.04      , 0.03846154, 0.03703704, 0.03571429, 0.03448276,
       0.03333333, 0.03225806, 0.03125   , 0.03030303, 0.02941176,
       0.02857143, 0.02777778, 0.02702703, 0.02631579, 0.02564103,
       0.025     , 0.02439024, 0.02380952, 0.02325581, 0.02272727,
       0.02222222, 0.02173913, 0.0212766 , 0.02083333, 0.02040816,
       0.02      , 0.01960784, 0.01923077, 0.01886792, 0.01851852,
       0.01818182, 0.01785714, 0.01754386, 0.01724138, 0.01694915,
       0.01666667, 0.01639344, 0.01612903, 0.01587302, 0.015625  ,
       0.01538462, 0.01515152, 0.01492537, 0.01470588, 0.01449275,
       0.01428571, 0.01408451, 0.01388889, 0.01369863, 0.01351

In [ ]:
arr**3

array([     0,      1,      8,     27,     64,    125,    216,    343,
          512,    729,   1000,   1331,   1728,   2197,   2744,   3375,
         4096,   4913,   5832,   6859,   8000,   9261,  10648,  12167,
        13824,  15625,  17576,  19683,  21952,  24389,  27000,  29791,
        32768,  35937,  39304,  42875,  46656,  50653,  54872,  59319,
        64000,  68921,  74088,  79507,  85184,  91125,  97336, 103823,
       110592, 117649, 125000, 132651, 140608, 148877, 157464, 166375,
       175616, 185193, 195112, 205379, 216000, 226981, 238328, 250047,
       262144, 274625, 287496, 300763, 314432, 328509, 343000, 357911,
       373248, 389017, 405224, 421875, 438976, 456533, 474552, 493039,
       512000, 531441, 551368, 571787, 592704, 614125, 636056, 658503,
       681472, 704969, 729000, 753571, 778688, 804357, 830584, 857375,
       884736, 912673, 941192, 970299])

## Universal Array Function
### Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are just mathematical operations you can use to perform the operation across the array. Some common ones:

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ,
       7.07106781, 7.14142843, 7.21110255, 7.28010989, 7.34846923,
       7.41619849, 7.48331477, 7.54983444, 7.61577311, 7.68114575,
       7.74596669, 7.81024968, 7.87400787, 7.93725393, 8.        ,
       8.06225775, 8.1240384 , 8.18535277, 8.24621125, 8.30662386,
       8.36660027, 8.42614977, 8.48528137, 8.54400375, 8.60232

In [ ]:
np.max(arr)

99

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
       -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388,
       -0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
       -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539,
        0.74511316, -0.15862267, -0.91652155, -0.83177474,  0.01770193,
        0.85090352,  0.90178835,  0.12357312, -0.76825466, -0.95375265,
       -0.26237485,  0.67022918,  0.98662759,  0.39592515, -0.55878905,
       -0.99975517, -0.521551  ,  0.43616476,  0.99287265,  0.63673801,
       -0.30481062, -0.96611777, -0.7391807 ,  0.1673557 ,  0.92002604,
        0.82682868, -0.02655115, -0.85551998, -0.89792768, -0.11

In [ ]:
np.log(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583,
       3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
       3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165,
       3.68887945, 3.71357207, 3.73766962, 3.76120012, 3.78418963,
       3.80666249, 3.8286414 , 3.8501476 , 3.87120101, 3.8918203 ,
       3.91202301, 3.93182563, 3.95124372, 3.97029191, 3.98898405,
       4.00733319, 4.02535169, 4.04305127, 4.06044301, 4.07753744,
       4.09434456, 4.11087386, 4.12713439, 4.14313473, 4.15888308,
       4.17438727, 4.18965474, 4.20469262, 4.21950771, 4.2341065 ,
       4.24849524, 4.26267988, 4.27666612, 4.29045944, 4.30406

In [ ]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462,
        0.40808206, -0.54772926, -0.99996083, -0.53283302,  0.42417901,
        0.99120281,  0.64691932, -0.29213881, -0.96260587, -0.74805753,
        0.15425145,  0.91474236,  0.83422336, -0.01327675, -0.84857027,
       -0.90369221, -0.12796369,  0.76541405,  0.95507364,  0.26664293,
       -0.66693806, -0.98733928, -0.39998531,  0.5551133 ,  0.99984331,
        0.52532199, -0.43217794, -0.99233547, -0.64014434,  0.30059254,
        0.96496603,  0.7421542 , -0.16299078, -0.91828279, -0.82930983,
        0.02212676,  0.85322011,  0.89986683,  0.11918014, -0.77108022,
       -0.95241298, -0.25810164,  0.67350716,  0.98589658,  0.39185723,
       -0.56245385, -0.99964746, -0.5177698 ,  0.44014302,  0.99