<a href="https://colab.research.google.com/github/MelsonHeo00/Summer_MicroCredential/blob/main/Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Problems

____________

#### Import NumPy as np

In [ ]:
import numpy as np

#### Create an array of 20 zeros 

In [ ]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

#### Create an array of 10 ones

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [ ]:
arr = np.arange(10)
arr[:] = 5
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
my_matrix = [[0,1,2],[3,4,5],[6,7,8]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Create a 3x3 identity matrix

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [ ]:
np.random.rand(1)

array([0.62667361])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
np.random.randn(5,5)

array([[-0.66271835,  0.70944322,  0.49192808, -0.829124  ,  0.32320414],
       [ 2.02235862, -0.98207225,  0.1412907 ,  0.67459766, -1.00086403],
       [ 2.62153152,  0.33925309,  0.65830137,  0.36113734, -0.53305423],
       [ 0.19539086,  0.28665254,  1.30959115, -0.44766827,  1.65078185],
       [ 0.70721563,  1.23361349, -0.12389451, -1.45353956, -0.62382594]])

#### Create the following matrix:

In [ ]:
arr = np.arange(0.01,1.01,0.01)
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [54]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
mat

# Note: I had to alter the matrix a bit to fit the context of both of the sections
# Changes: 27 -> 26

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [83]:
new_array1 = mat.reshape(25,1) # Reshapes the entire matrix to 25, 1
array1 = new_array1[11:25] # Acquires the array that is between 12 and 25
bool_arr = array1 != 16 # Conditions all of the numbers where it does not equal to 16
array2 = array1[bool_arr] # Gets rid of the 16 within the matrix
bool_arr1 = array2 != 21 # Conditions all of the numbers where it does not equal to 21
array3 = array2[bool_arr1] # Gets ride of the 21 within the matrix
array3.reshape(3,4) # Outputs the code with the reshape where it becomes 3, 4

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [65]:
mat[3][4] # Row 3, Column 4

20

20

In [59]:
new_array1 = mat.reshape(25,1) # Reshapes the entire matrix to 25, 1
array1 = new_array1[1] # Finds the 2 within the matrix
array2 = new_array1[6] # Finds the 7 within the matrix
array3 = new_array1[11] # Find the 12 within the matrix
output = np.concatenate((array1, array2,array3)) # I searched this function online to combine the 3 arrays
# Concatenate allows to combine any arrays within the ()
output.reshape(3,1) # Outputs the code with the reshape 3,1

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [89]:
bool_array2 = 20 < mat
mat[bool_array2] 

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [88]:
bool_array3 = 15 < mat
mat[bool_array3].reshape(2,5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now,

In [47]:
# Note: For this section, I used the mat = np.arange(1,27).reshape(5,5) but everytime I ran this matrix, it gave me an error. Therefore, I changed the 27 to 26
mat = np.arange(1,26).reshape(5,5)

#### Get the sum of all the values in mat

In [62]:
np.sum(mat)

325

325

#### Get the standard deviation of the values in mat

In [63]:
np.std(mat)

7.211102550927978

7.2111025509279782

#### Get the sum of all the columns in mat

In [64]:
np.sum(mat, axis = 0)

array([55, 60, 65, 70, 75])

array([55, 60, 65, 70, 75])

# Cheers!